env:
  global:
    # Required for our sanity
    - THE_ONE_TWO_NINE="This is about: "

language: c

git:
  depth: 51

branches:
  except:
  - gh-pages

matrix:
  include:
  - os: linux
    compiler: gcc
  - os: osx
    compiler: clang

sudo: false

install: true

addons:
  apt:
    packages:
    - texinfo
    - guile

script:
 - ./t/0001-who-is-this
 - echo "${THE_ONE_TWO_NINE} TRAVIS_OS_NAME='${TRAVIS_OS_NAME}'"
 - git branch
 - guile -c '(display "Hello, 120")(newline)'
