language: c
sudo: false
install: true
addons:
  apt:
    packages:
    - rubber
    - latex-beamer
    - xsltproc
script:
- ./t/0001-who-is-this
- ./t/0002-rubber-pdf-doc
- ./t/0004-static-pages
- rm -f doc/*.{aux,log,nav,out,snm,toc,bak}
- git stash --all
env:
  global:
    secure: ABOyq5RiOFKhVczolqbfgGD6ahwEWqHA6i3Hg9iHsuchmkmHvdqtK79D/1+eGsTwRKQ4GDQbhSUXxwURlc/mIb1hhksnBFU43Qo+G0mVJYidQxxwvlIyIRolwk9gJ1WRCzAptjFuSSJngA8wE0c3RhCyPhgQKxCXdIH/Zpsvhwkw6x8OA2s0femm7RTaxWnO4hb0TjTqRK65WYTSqjqo1Tnzo6RzL969/p5Nct46uBJB/vgWsAUajlaI5aORiK2AkDprywyJ7heaLicVtCS49yKEXv3h2G358jOxGDypngYPWOo6Y9FSV2Aw67HWuo3nGNpg46SOMLmfY/6aG14KjlZJZ5B0MWJgVJ0VJeP58fP3CohDybRN8A+u3pzN9eSqB7L6J+LBjHcXMqNceeyhiDhwxHp/YgaMKqIdz0B+eIQt389ihkFqwykRjtbNXFL58p+JoX/ZDp23PmXOJmlbLca1oyOn3clUr2J2inBdlaM05vdTRtTVASGJtIBntCJFHaEifiaO6ose+fwOwITW4Kn4gg5zIY+AOtEetQq8f5pHQ/Oq5Qy2d55hlrXVNaMNFrDSQd1Wp8gsOPKr3GXSGoQswHSuOTnrYeD4b+idrijeNrZJQsPqH/X2R1/ZSEe+UtNiuM5g6DDptzWXYSyLkZeC29aGf7+zCGbs5U/bZkA=
deploy:
  provider: pages
  skip-cleanup: true
  github-token:
    secure: P1Jp6f6ypypgrwpF8NYC0lqAmQ8gRm+JYgyIlUbQyQh6NGX0tuLpWmbHm7djMJJ9wV/tKF9tMdk0AOIGTsJMNWbktQfCE5umdjrVOO4baQ0edGbYE1tiplxpSbdj6tcgoUPEmO7Rdpos2H1eWFGUqdj9SoXRFs5pDawFt2CmMkuoecq/j6S8xpDRvE7iDC92cuxpRaeuwhbPKastlUZKZWDSiwmgKP+I0AqZGbGuHNTTQ8VKDJLtm+vKdsVxXD7ENgsn1IPgVZPyekIjQ3D2nqwgR2U4/LBvVjHU/V8hO8PCDbupccBg2jQq2Hesf3bcKbh8Op9gRIox4CKea6tllUNYoCtcwt4MQiu1B6Qs8pdeuwe8jpMIeFTDMIv+7J3kvFtdCYQZ953zpBcGrdgKK52RlfwV2Rz47zvpPBo6JcCLNBgLGWc6MFC1+7/un5lVSWcg/zmPI2f7e+ndLBbW4sasAcgxeJFBtKNo1XizNwSpK+8nMxP7dvGY0+AIiCAqh4KHZrR4iQaA5jM03mMktPOdc2wx1c8crx0Rz5cIZpORlXsjovfbyYIc9TnnEGShRh4YghAHW3vxYpVxLjT9VIaG+rUEqcACp8PHqIKcGqJrDR6FyLlQNXM+Ia3kQG2i4ynMHOEqmsxVvNc3oIgFaEFjhXb8kCFil717AP9H2Iw=
  keep-history: true
  on:
    branch: feature/0006/static-pages
  verbose: true
  local-dir: ./
